### ISSUE TITLE
Text reflow issue during animation

### ISSUE THREAD

**Issue by betweenbrain** [rygine/looper#7]
I've discovered that if a looper item contains text, and is also padded, the text is full-width during animation. I've created an exagerated demo at http://jsfiddle.net/betweenbrain/Ewe9N/4/ to illustrate the issue.

Any thoughts?

**Comment by rygine** [comment]
This is a result of the next/previous slides being positioned absolutely with a width of 100% of it's parent container. When you add that extra padding, the width of those slides becomes 100% + the padding while it's sliding into view. I'll look into the use of position relative for the sliding animation, but there's an easy fix right now. Use box-sizing: border-box; for the .item. I highly recommend that your entire site/app use box-sizing: border-box. It feels much more natural, at least to me.

**Comment by betweenbrain** [comment]
Thanks! I appreciate the fix and recommendation. To be honest, I haven't been using box-sizing: border-box as I've had to support IE7 until just recently. I guess I'm still in the process of breaking out of that mindset.

Keep up the great work, we appreciate it!
